name: CI Run Ruff Lint

on:
  pull_request:
    # PR merge ruleに設定してるので指定外のpathのみのPRだと発火せずにPRをmergeできないため
    # paths:
    #   - '**.py'
    #   - '**.pyi'
    #   - 'pyproject.toml'
    #   - "uv.lock"
    #   - "pyrightconfig.json"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Ruff Lint Check
    steps:
      - name: Check out codebase
        uses: actions/checkout@v5
      
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.18"
          # キャッシュの読み込み
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --group lint --no-dev

      # Ruffの実行
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-ruff-to-lint-code
      - name: Lint with Ruff
        run: |
          uv run ruff check . --output-format=github
