name: CI Run Tests

on:
  pull_request:
  # PR merge ruleに設定してるので指定外のpathのみのPRだと発火せずにPRをmergeできないため除外
    # paths:
    #   - '**.py'
    #   - '**.pyi'
    #   - 'pyproject.toml'
    #   - "uv.lock"
    #   - "pyrightconfig.json"
    #   - "pytest.toml"
  workflow_dispatch:

jobs:
  test:
    name: Pytest Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out codebase
        uses: actions/checkout@v5
      
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.18"
          # キャッシュの読み込み
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --group test --no-dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest